name: Job Dependency Demo

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build step
        run: echo "🔧 Building project..."

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Run tests
        run: npm test
      # Optional: Uncomment to simulate failure
      # - name: Simulate test failure
      #   run: exit 1

  deploy:
    needs: test
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Conditional deploy
        run: echo "Deploying to production branch..."
